server:
  port:  8082
  servlet:  
    contxt-path:  /SpringBootApplication
    session:
      timeout:  30m
    multipart:
      enabled:  true                     #文件上传支持
      file-size-threshold:  0            #写入磁盘阈值
      location:  D:\\TEMP                #临时保存位置
      max-file-size:  10MB               #单文件最大
      max-request-size:  10MB            #多文件总大小
      resolve-lazily:  false             #文件是否延迟解析
  tomcat:  
    uri-encoding:  utf-8
  error:
    path:  /error
#spring:
#  mvc:
#     static-path-pattern:  /static/**    #过滤规则
#  resources:
#     static-locations:  /static/         #静态资源位置